### ISSUE TITLE
About more metrics

### ISSUE THREAD

**Issue by bruno686** [divelab/GOOD#29]
Hi Shirui,
   The code only seems to show one metric at a time, how can I set it up to show F1, Accuarcy, etc. at the same time?

**Comment by CM-BF** [comment]
Hi Zhuangzhuang,

The easiest implementation will be to modify the [`eval_score` function ](https://github.com/divelab/GOOD/blob/fff0e2dc311e1d0e0a23052f6c601db4f185e12e/GOOD/utils/evaluation.py#L60) so that it includes a new parameter for the selection of the score function like F1, Accuracy. Then you can add your `eval_score` calls in the [`evaluate` function](https://github.com/divelab/GOOD/blob/fff0e2dc311e1d0e0a23052f6c601db4f185e12e/GOOD/kernel/pipelines/basic_pipeline.py#L217) for different metrics and output them. Note that although you can output different metrics, we generally use one metric to select the best model. If your goal is to choose the best model using multiple metrics, a good practice is to define a new "score" as the mixture of the current metrics. For more complex model selection algorithms, you may need to write your code.

Best

**Comment by bruno686** [comment]
You're really a good boy! Thank you very much!
