### ISSUE TITLE
Circular Import error

### ISSUE THREAD

**Issue by ghost** [divelab/GOOD#8]
Hello @divelab,
n my opinion, this repository's code is amazing and very clean. It is very helpful to use others. My case involves a `Circular Import error` bug, which I fixed by changing two files in this repository:

1. `GOOD/data/__init__.py` file i changed

```
from .good_datasets import *
from .good_loaders import *
```

to

```
from GOOD.data.good_datasets import good_arxiv, good_cbas, good_cmnist, good_cora, good_hiv, good_motif, good_pcba, good_sst2, good_twitch, good_webkb, good_zinc
from GOOD.data.good_loaders import BaseLoader
```

2. `GOOD/data/good_datasets/__init__.py` file i changed

```
from . import *
```

to

```
import good_arxiv, good_cbas, good_cmnist, good_cora, good_hiv, good_motif, good_pcba, good_sst2, good_twitch, good_webkb, good_zinc
```

Please update the repository if you believe this is a global issue.

**Comment by CM-BF** [comment]
Hi amirshnll,

[This import code](https://github.com/divelab/GOOD/blob/GOODv1/GOOD/data/good_datasets/__init__.py) serves for a unique feature: You can create any new dataset classes and register them without any modifications of the `__init__.py` file. Using this repo won't cause this issue since the code always passes the training test.

Can you tell me which GOOD version you are using and post your error log for me to check? I would like to help you with this issue. 😄 

Best,
Shurui

**Comment by ghost** [comment]
I used the repository sample code in documentation:

https://good.readthedocs.io/en/latest/tutorial.html#good-datasets

but not in a personal dataset.

**Comment by CM-BF** [comment]
I have just tried the code:
```python
# Directly import
from GOOD.data.good_datasets.good_hiv import GOODHIV
hiv_datasets, hiv_meta_info = GOODHIV.load(dataset_root, domain='scaffold', shift='covariate', generate=False)
# Or use register
from GOOD import register as good_reg
hiv_datasets, hiv_meta_info = good_reg.datasets['GOODHIV'].load(dataset_root, domain='scaffold', shift='covariate', generate=False)
cmnist_datasets, cmnist_meta_info = good_reg.datasets['GOODCMNIST'].load(dataset_root, domain='color', shift='concept', generate=False)
```
and didn't meet the problem you mentioned.

Please let me know if the issue persists.
